version: '3.1'

services: 
  mysql:
    build : .
    image : declue/mysql:5.7
    container_name: mymysql
    restart: always
    ports: 
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=testtest
